table Glossary
	lineageTag: d01d13f7-8f9f-45ae-a3d2-aeb3efb0309f

	column Column1
		dataType: string
		lineageTag: 7e9be0fb-f597-4d30-a1a7-36dace4b6e80
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 4cb1de35-e3da-4687-ad5d-37ce48892bd4
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	partition Glossary = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\PrestonCutler\OneDrive - Vaco\Desktop\Main\Client Projects\GitRepo MFCPC17\MFCCyberPBI\TruGreen - 2024 - Glossary.xlsx"), null, true),
				    Glossary_Sheet = Source{[Item="Glossary",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Glossary_Sheet,{{"Column1", type text}, {"Column2", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

